# Generated by Django 5.0.14 on 2026-05-11 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userasset',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userasset',
            constraint=models.UniqueConstraint(fields=('user', 'symbol'), name='unique_user_symbol'),
        ),
    ]
